---

services: docker

if: (type = pull_request) OR (branch = master)

env:
  matrix:
  - distro: centos:7
    playbook: test.yml
  - distro: 'ubuntu:16.04'
    playbook: test.yml
  - distro: 'ubuntu:18.04'
    playbook: test.yml
  - distro: debian:8
    playbook: test.yml
  - distro: debian:9
    playbook: test.yml
  - distro: debian:10
    playbook: test.yml
  - distro: fedora:27
    playbook: test.yml
  - distro: fedora:28
    playbook: test.yml
  - distro: 'ubuntu:18.04'
    playbook: test_networktopology.yml

matrix:
  allow_failures:
    - env: distro=debian:10 playbook=test.yml
    - env: distro=fedora:28 playbook=test.yml

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  # run ci tests
  - ${PWD}/tests/runtests.sh
  - pip install --user https://github.com/openwisp/openwisp-utils/tarball/master
  - |
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      # gets commit message of last commit before pull request merge
      COMMIT_MESSAGE=$(git log $TRAVIS_PULL_REQUEST_SHA --format=%B -n 1)
      printf "Checking commit message:\n\n"
      printf "$COMMIT_MESSAGE\n\n"
      checkcommit --message "$COMMIT_MESSAGE"
    fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
